### ISSUE TITLE
Borders of 1492 China

### ISSUE THREAD

**Issue by timmhayes** [aourednik/historical-basemaps#12]
Like in a previous issue, I saw your data reused on https://historicborders.app/ via a Reddit post. Please check out the borders of Laos in 1492, which extend across China. I'm pretty sure that should be labeled under the Ming dynasty.

**Comment by aourednik** [comment]
My knowledge of 1492 Laos is very limited. Could you send me a corrected file for this year? Best would be a pull request, but you can also mail me a geojson file and I will update on this repository

**Comment by timmhayes** [comment]
Here you go, pull request: https://github.com/aourednik/historical-basemaps/pull/13

**Comment by aourednik** [comment]
Thank you. It is merged now.
