### ISSUE TITLE
Readme - Weidemann domain for sale

### ISSUE THREAD

**Issue by andxblink** [aourednik/historical-basemaps#17]
Thank you for the great resource. A quick info:

In your readme > "Some (rare) historical georefernced resources on the web"
**CShapes by Niels Weidman, also available as an R package**
[http://nils.weidmann.ws/projects/cshapes.html](http://nils.weidmann.ws/projects/cshapes.html)

The linked domain seems to be for sale / offline

**Comment by aourednik** [comment]
Thanks for pointing this out. URL updated to https://icr.ethz.ch/data/cshapes/
