### ISSUE TITLE
bc1 is slightly rotated compared to the others

### ISSUE THREAD

**Issue by Fil** [aourednik/historical-basemaps#2]
I've made an observable to look at your files, and with the animation it appears that there is a slight rotation on bc1

https://beta.observablehq.com/@fil/historical-basemaps-take-1

(note that you might fork my animation and ask me to take it off — it's really not ready to "publish", but it was the simplest way to share)

**Comment by aourednik** [comment]
This should be fixed now. Can you confirm?
I would't call it "André Ourednik's dataset", though. For now, these are amended files of a very old  anonymous dataset referenced here : https://www.gislounge.com/find-gis-data-historical-country-boundaries/  and only accessible through the TimeMachine  http://web.archive.org/web/20080328161758/http://library.thinkquest.org:80/C006628/disclaimer.html
I've corrected the coarsest error (an over 20km shift) and added some anncient regions. But the set still needs a lot of work. Completing, harmonizing transhistorically, let the regions overlap where they should and add a "border approximation index" for ancient regions, to be able to use a gradient border like this https://bl.ocks.org/pbogden/14864573a3971b640a55 in D3 rendering, for instance. Point layers for cities should also be added. Thus I am looking for GitHub contributors. To my kowledge, this would be the first, non-institutional, simple to retrieve, free and conntributive dataset for historical base maps on the world scale.

**Comment by Fil** [comment]
- Fix Confirmed

- I changed the wording to "curated by André Ourednik"

- I'm in!  👍
