### ISSUE TITLE
Lack of history in pacific islands

### ISSUE THREAD

**Issue by gursantsingh** [aourednik/historical-basemaps#26]
Would be nice to see some more history in polynesia, melanesia, and micronesia. Would be nice to see the tui'tonga empire and rapa nui.

**Comment by aourednik** [comment]
Good point. Tuʻi Tonga Empire added. Might need rectification in early years and final years. 
For the Rapa Nui, more complicated: the very term "Rapa Nui" (Great Rapa) is posterior to repopulation by polynesians from Rapa and Gambier islands, after the genocide by Peruvian slave traders commited around 1860. Prior to that the population of the island was Matamua ou Haumaka, but the names seem anchored in an oral tradition harder to verify
