### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thisisaaronland** [aourednik/historical-basemaps#3]
Hi,

What is the licensing for this data? If appropriate it seems like a valuable dataset to import / hold hands with Who's On First:

https://whosonfirst.org/

Historical data always took a back seat to other day-to-day concerns but it was (is) definitely still something we want to support:

https://whosonfirst.org/blog/2017/06/29/tackling-space-and-time-in-whosonfirst/

**Comment by aourednik** [comment]
Hi,
Thaks for pointing that out. I've added a licence file. https://github.com/aourednik/historical-basemaps/blob/master/LICENSE

**Comment by thisisaaronland** [comment]
Alas, the license makes it incompatible with WOF :-)

Cheers,
