### ISSUE TITLE
De facto boundaries

### ISSUE THREAD

**Issue by maptracer** [aourednik/historical-basemaps#32]
In the interests of historical accuracy it may be useful to know which countries actually controlled which territories at a given moment of time. Also, GIS files without polygon overlaps are better for making choropleth maps. For those purposes it would be better to add separate maps with de facto country boundaries for each year. If you are interested, I can start making them.

**Comment by aourednik** [comment]
"GIS files without polygon overlaps are better for making choropleth maps" : Not in all cases. Overlapping borders render disputed territories (not standard GIS practice, I know, but the standard GIS practice has been mainly formalized by engineers and geophysicist)
I wish to keep this repository simple: 1 file per reference year.
Feel free to fork though
