### ISSUE TITLE
Border precision

### ISSUE THREAD

**Issue by maptracer** [aourednik/historical-basemaps#34]
What is the difference between the values 1 (approximate) and 2 (moderately precise) in the BORDERPRECISION field?

Also, some parts of the same boundary between two countries may be precise and undisputed, and other parts may be undemarcated (as in the case of the South Patagonian Ice Field between Argentina and Chile) or disputed (as in the case of Kashmir between India and Pakistan). Wouldn't it be better to delete this field from multipolygon maps and make separate multilinestring maps showing different parts of boundaries marked with different codes (such as undisputed, claimed or approximate) that could be visualized using different line types (solid, dashed, dotted) instead of declaring the whole country as having "approximate" boundaries and drawing it as a blurry blob (https://raw.githubusercontent.com/aourednik/historical-basemaps/master/img/historicBorders_fuzzyNonFuzzy.png)? If you are interested, I can start making them.

**Comment by aourednik** [comment]
BORDERPRECISION:  1 e.g. the Beaker or Afanasevo culture. 2: The Holy Roman Empire,
Disputed borders are rendered as overlapping polygons, each country occupying its maximum perceived extent (not standard practice in GIS, but hardly anyone will run topology-dependent geospatial calculations on these basemaps, where such overlaps could become an issue; most GIS fundaments have been conceptualized by engineers and physical geographers; in cultural geography, space occupation is non-exclusive)
Multipolygon vs Multilinestring: Conceptually, I am not convinced in a 2D territory rendered as its 1D border(s). Also, maintaining over 30 multipolygon layers is already quite a task.  I get your idea, though, if your research is border-focused. Don't hesitate to fork the repositry with a multilinestring version
