### ISSUE TITLE
PARTOF field

### ISSUE THREAD

**Issue by maptracer** [aourednik/historical-basemaps#35]
What is the exact purpose of the PARTOF field? Is it necessary for new contributions? Usually it just duplicates the SUBJECTO field.

Since it is usually difficult do ascribe each country to a single "larger cultural area", this field could be used to list international organizations and alliances that the country is a member of (like this: https://www.cia.gov/the-world-factbook/field/international-organization-participation/), but gathering necessary information for each year may take a lot of time.

**Comment by aourednik** [comment]
The field can simply be NULL. Mainly used in Ancient HIstory, but must be present in all layers for consistency.
Feel free to use it any way you like in your own project
