### ISSUE TITLE
Nothing's showing up

### ISSUE THREAD

**Issue by Nuffieldcool** [aourednik/historical-basemaps#39]
![notworking](https://github.com/aourednik/historical-basemaps/assets/167892060/91c9cffd-8992-415a-a248-662d9701983d)
So, i watched Boone Loves Video's tutorial, and i folowed eveything and have retried, i have restarted both after affects and my pc. The source is showing up, but when i search for anything, i only get places name, and not any historical maps. This is really annoying!

**Comment by Celalvekerem** [comment]
Same problem here, nothing shows up.

**Comment by aourednik** [comment]
This seems unrelated to this repository
