### ISSUE TITLE
Ukraine 1920s borders

### ISSUE THREAD

**Issue by AbdulazizOmran** [aourednik/historical-basemaps#42]
i noticed an error in the 1920 geojson map in which Crimea is a part of Ukraine, Crimea was transferred to the Ukrainian SSR by the Russian SFSR inside of the Soviet Union in 1954. in 1920, it was still a part of the RSFSR, even before the Creation of the Soviet Union

**Comment by aourednik** [comment]
Thanks for pointing to that issue. Most of 1920, it was rather under jusrisdiction of the White movement, as South Russia.
https://en.wikipedia.org/wiki/South_Russia_(1919%E2%80%931920)
Precision added to map.
