### ISSUE TITLE
File encoding

### ISSUE THREAD

**Issue by idris-maps** [aourednik/historical-basemaps#5]
What is the file encoding you use for the geojson files?

It looks like UTF-8 but some words have these `?` characters. Tried a couple, in my experience the problem usually is some special windows encoding, but could not find which one it was.

Example: 
![image](https://user-images.githubusercontent.com/12154856/81148086-e9886180-8f7b-11ea-98b6-ee42d635079d.png)

**Comment by idris-maps** [comment]
I downloaded directly from the internet archive. Seems like it was some windows encoding. Here is what I got if you are interested: https://github.com/idris-maps/world-historical-gis-data

**Comment by aourednik** [comment]
Hi. All files are inteded to use UTF-8. If you see erroneous characters, do not hesitate to correct them and file pull requests. Please just make sure all files remain UTF-8 encoded.
